merge frontend implementation of everything minus checkout page and admin page
ksmarty/CartCrafters pull request #15
Opened 2023-08-13 22:52 UTC by levkropp

login page and register page have visible text and submit form buttons with functions ready for backend implementation
shopping cart works, can be passed to anything between the header and footer 
shopping cart page displays a table and checkout button

2023-08-13 23:49 UTC, ksmarty requested changes

2023-08-13 23:49 UTC, ksmarty commented on frontend/README.md
We don't need this file

2023-08-13 23:49 UTC, ksmarty commented on frontend/firebase-debug.log
We don't need this file

2023-08-13 23:49 UTC, ksmarty commented on frontend/pages/certs.js
We don't need this, right?

2023-08-14 00:02 UTC, levkropp commented on frontend/README.md
yeah i guess

2023-08-14 00:03 UTC, levkropp commented on frontend/pages/certs.js
no, this was a blank page i just copied when making new pages/Components but we don't need it in the repo

2023-08-14 00:20 UTC, ksmarty approved these changes

2023-08-14 01:12 UTC, merged